data:datapoints.py
	python datapoints.py
train: train_test.py
	python train_test.py dataset.txt
scale:
	python scale_train_test.py dataset.txt
clean:
	rm *.model
	rm *.test
	rm *.train
	rm *.out
	rm *.result
	rm *.scale
	rm *.png
	rm *.txt